export const foodCarbonData = [
    { name: "Butter Chicken", emission: 2.1 },
    { name: "Chicken Biryani", emission: 2.5 },
    { name: "Mutton Rogan Josh", emission: 4.5 },
    { name: "Fish Curry", emission: 1.8 },
    { name: "Egg Curry", emission: 1.0 },
    { name: "Paneer Butter Masala", emission: 1.6 },
    { name: "Palak Paneer", emission: 1.5 },
    { name: "Dal Makhani", emission: 0.9 },
    { name: "Rajma Chawal", emission: 0.85 },
    { name: "Chole Bhature", emission: 1.2 },
    { name: "Vegetable Pulao", emission: 0.8 },
    { name: "Masoor Dal (Red Lentil Curry)", emission: 0.6 },
    { name: "Tandoori Chicken", emission: 2.0 },
    { name: "Biryani (Veg)", emission: 1.0 },
    { name: "Samosa (2 pcs)", emission: 0.5 },
    { name: "Pav Bhaji", emission: 0.7 },
    { name: "Idli (3 pcs)", emission: 0.4 },
    { name: "Dosa (1 pc)", emission: 0.5 },
    { name: "Vada Pav", emission: 0.6 },
    { name: "Pani Puri (6 pcs)", emission: 0.4 },
    { name: "Poha", emission: 0.3 },
    { name: "Upma", emission: 0.4 },
    { name: "Khichdi (Dal + Rice)", emission: 0.7 },
    { name: "Aloo Paratha (2 pcs)", emission: 0.6 },
    { name: "Rasgulla (2 pcs)", emission: 0.7 },
    { name: "Gulab Jamun (2 pcs)", emission: 0.8 },
    { name: "Jalebi (100g)", emission: 0.5 },
    { name: "Kheer (Rice Pudding)", emission: 0.9 },
    { name: "Lassi (1 glass)", emission: 0.6 },
    { name: "Masala Chai (1 cup)", emission: 0.2 },
];
